apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs
  namespace: webapp-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp-container
        image: webapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service.mysql-ns.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: DBUSER
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: DBPWD
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: DATABASE
        - name: APP_COLOR
          value: "blue"
